# Generated by Django 2.0.13 on 2019-07-14 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Some Name', max_length=50, unique=True)),
                ('birthday', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='articles',
            name='authors',
            field=models.ManyToManyField(through='authors_app.ArticleAuthor', to='authors_app.Authors'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='article_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors_app.Articles'),
        ),
        migrations.AddField(
            model_name='articleauthor',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors_app.Authors'),
        ),
    ]
